### ISSUE TITLE
openshiftApply step unit test

### ISSUE THREAD

**Issue by dtschan** [puzzle/jenkins-pipeline-shared-libraries#18]
Implement unit test for openshiftApply step which tests:

* Works whether oc is in PATH or not
  * Installs oc if not in PATH
* Executes `oc convert -f ${tmpfile}` to validate **configuration** argument
  * Where **tmpfile** contains the **configuration** argument of the step
  * Fails when **configuration** is invalid, e.g.

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: mycontainer        
        resources:
          limits:
            cpu: 1   # Wrong type, must be a string
...
```            
            
or:

```yaml
apiVersion: v1  # Unknown type, API group is missing
kind: DeploymentConfig
...
```

* Executes `oc apply -f ${tmpfile} -l "app=${appLabel}" --prune`
  * Where **tmpfile** contains the value of **configuration**
* if **waitForRollout** is true:
  * if **rolloutSelector** is not provided:
    * Executes `oc rollout status ${rolloutKind}/${appLabel}`
  * else
    * Executes `oc rollout status ${rolloutKind}/${object}` for every **rolloutKind** object matched by **rolloutSelector**
